### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by ecustovic** [nerdgeschoss/pixelpress#17]
Hi! Could you please help me how to fix current bug in my project and what should I setup to get specific encoding, to be more precisely: Slavic ones? Here is the output of my pdf report.
![image](https://user-images.githubusercontent.com/41287225/74016737-3a93b400-4993-11ea-91a8-0e88075d7a83.png)

**Comment by JensRavens** [comment]
Hello @ecustovic,
nice to see that someone outside of our company is using this gem. We're using this for several internal projects that all use UTF-8 encoding, including german umlauts and some japanese characters and all of them work. So my guesses are:

- did you check everything is used and sent in UTF-8?
- maybe the UTF-8 meta-tag is missing from your html template? (`<meta name="charset" content="utf-8"/>`)

You can try to render out in html (`printer.your_method.html`) or use a preview to get the html version. If it does render correctly in the browser, also Weasyprint should be able to handle it.
