### ISSUE TITLE
[Docs] Add note that WeasyPrint package is required

### ISSUE THREAD

**Issue by McBen** [nerdgeschoss/pixelpress#26]
without Weasyprint you only get a
`> Errno::ENOENT (No such file or directory - ):` 
when trying to create a pdf. There is no hint what the real problem is.

maybe with a installation link: https://doc.courtbouillon.org/weasyprint/stable/first_steps.html

additional:
https://github.com/nerdgeschoss/pixelpress/blob/621685cac90ad5bd5dbba5000606466a9c683165/lib/pixelpress/renderers/weasyprint_renderer.rb#L16C5-L16C82
won't raise an error because the 'which" result is an empty string and ruby treats it as `true`

**Comment by JensRavens** [comment]
Good catch! I'll look into it.
